Tugule/urls.py
from django.contrib import admin
from django.urls import path,include

app_name = 'Tugule'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugulenga.urls',namespace='tugule')),
    path('products/',include('products.urls',namespace='products')),
    path('', include(('Tugule.urls', 'Tugule'), namespace='Tugule')),


]

products/urls.py
from django.urls import path
from . import views
app_name="products"
urlpatterns=[
    path('',views.home,name="home"),
    
    path('cart/',views.cart,name="cart"),
    path('delete_order/<str:product_id>',views.deleteOrder,name="delete_order"),
    path('category/<str:category_id>', views.products, name='category'),
    path('update_item/', views.update_item, name='update_item'),
    path('checkout/',views.checkout,name="checkout"),
  
]

tugulenga/urls.py
from django.urls import path
from . import views
app_name="tugule"
urlpatterns=[
    path('',views.home,name="home"),
    path('signup/',views.signup,name="signup"),
    path('login/',views.loginPage,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('add_product/', views.add_product, name="add_product"),
    path('profile/', views.profileForm, name= "profile"),
     
]

tugulenga/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Creating  models here.
class Profile (models.Model):
    user = models.OneToOneField(User,null=True, on_delete=models.CASCADE) # One to one relationship with the User model.
    # image = models.ImageField(default='avatar.png', upload_to= 'profile/', blank=True)
    contact = models.CharField(max_length = 50, default='07893672948')
    name = models.CharField(max_length = 200, default = user)

  
    

    def __str__(self):
        return f'{self.user.username} Profile'
    
    #save the profile
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        
        # img = Image.open(self.image.path)
        # if img.height > 300 or img.width > 300:
        #     output_size =(300,300)
        #     img.thumbnail(output_size)
        #     img.save (self.image.path)

    

#created this model for database table for the the business account
class Business_account(models.Model):

    owner= models.OneToOneField(User,on_delete= models.CASCADE, blank = True, null = True)
    name = models.CharField(max_length = 100)
    phone = models.CharField(max_length =20)
    email = models.EmailField()
    location = models.CharField(max_length = 255)
    description = models.TextField()
    logo = models.ImageField(upload_to='Logos/', null= True, blank=True)
    
    

    def __str__(self):
        return self.name
    
class Category(models.Model):
    name= models.CharField(max_length=50)
    image =  models.ImageField( upload_to="Categories/", blank =True,null=True)

    def __str__(self):
        return self.name
    

#created this model for database table for the the Products  
class Product(models.Model):
        
        business_account= models.ForeignKey(Business_account, on_delete=models.CASCADE, null=True, blank=True )
        image =  models.ImageField( upload_to="Products/", blank =True)
        category=models.ForeignKey(Category,max_length=20, null=True,on_delete=models.CASCADE,blank=True)
        name = models.CharField(max_length=200, null=True)
        price = models.FloatField()
        
        def __str__(self):
            return self.name

    
#created this model for database table for the Order   
class Order(models.Model):
    customer = models.ForeignKey(User,on_delete= models.CASCADE, null=True,blank=True)
    date_ordered = models.DateTimeField(auto_now_add= True)
    complete = models.BooleanField(default=False, null=True,blank =False)
    

    def __str__(self):
        return str(self.id)
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


#created this model for database table for ordering items   
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, blank = True, null=True)
    customer = models.ForeignKey(Profile,on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name 
    @property
    def get_total(self):
        total = self.product.price *self.quantity
        return total

    


    





     
    

tugulenga/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import  UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import *



class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['image','category','name','price']

class Business_accountForm(ModelForm):
    class Meta:
        model = Business_account
        fields = '__all__'  

class OrderForm(ModelForm):
    class Meta:
        model=Order
        fields = '__all__'  

class OrderItemForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'

class  CreateUserForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username', 'email','password1', 'password2']

class ProfileForm(ModelForm):
    class  Meta:
         model=Profile
         fields=['contact','name']

tugulenga/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import Group
from django.contrib.auth.forms import  UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login ,logout
from .forms import CreateUserForm
from django.contrib import messages
from .decorators import unauthenticated_user
from .models import *
from .forms import *
# Create your views here.
def home(request):
    
    return render(request,'tugulenga/index.html')

@unauthenticated_user   
def signup(request):
     
    form = CreateUserForm()
    if request.method=='POST':
        form =CreateUserForm(data=request.POST)
        if form.is_valid():
                form.save()
                user=form.cleaned_data.get('username')

                messages.success(request,'Account was created for'+ user)
                return redirect('tugule:login')
            
    context={"form":form}
    return render(request,"tugulenga/signup.html",context)
     
@unauthenticated_user     
def loginPage(request):
   
    if request.method == 'POST':
        
        username = request.POST.get('username')
        password=request.POST.get('password')
        user = authenticate(request,username=username,password=password )
        if user is not None:
            login(request,user)
            return redirect('products:home')
        else:
        #    pass
           messages.info(request,'Username or Password is incorrect')
        
    return render(request,'tugulenga/login.html')

def logoutUser(request):
     logout(request)
     return redirect('tugule:home')

  
def add_product(request):
    business_account = Business_account.objects.get(owner = request.user)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            image= form.cleaned_data['image']
            category = form.cleaned_data['category']
            name = form.cleaned_data['name']
            price = form.cleaned_data['price']
            

            product = Product.objects.create(
                business_account = business_account,
                image=image,
                name = name,
                price = price,
                category = category,
            )
            product.save()
            return redirect('products:home')
    else:
        form = ProductForm()

    return render(request, 'tugulenga/add_product.html',{'form':form})
    
def profileForm(request):
    form = ProfileForm()
    return render(request, 'tugulenga/profile.html', {'form' : form })

tugulenga/templates/tugulenga/add_business_account.html
{%extends 'tugulenga/base.html' %}{% block content%}
<form class="auth" enctype="multipart/form-data" action="{% url 'tugule:add_business_account' %}" method="POST">
    {{form}} {% csrf_token %}
    <button class="auth" type="submit">Add</button>
</form>

{% endblock %}

tugulenga/templates/tugulenga/add_orderItem.html
{%extends 'tugulenga/base.html' %}{% block content%}
<form class="auth" enctype="multipart/form-data" action="{% url 'tugule:add_orderItem' %}" method="POST">
    {{form}} {% csrf_token %}
    <button class="auth" type="submit">Add</button>
</form>

{% endblock %}

tugulenga/templates/tugulenga/add_product.html
{%extends 'tugulenga/base.html' %}{% block content%}
<form class="auth" enctype="multipart/form-data" action="{% url 'tugule:add_product' %}" method="POST">
    {{form}} {% csrf_token %}
    <button class="auth" type="submit">Add</button>
</form>

{% endblock %}

tugulenga/templates/tugulenga/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    
    <style>
		body{
			background-color: rgba(198, 212, 227, 0.571);
		}
	</style>

  	
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/slide.css' %}">


  
	</head>
	
        <body>
          
            {% block content %}
            {% endblock %}
        </body>
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/popper.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/slides.js' %}"></script>
</html>

tugulenga/templates/tugulenga/index.html
{%load static%}
{%load bootstrap5%}
{%bootstrap_javascript%}

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Tugule</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" type="image/png" href="https://image.ibb.co/fOur3b/favicon.png"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel='stylesheet' href='https://cdn.rawgit.com/filipelinhares/ress/master/dist/ress.min.css'><link rel="stylesheet" href="{% static 'css/slide.css' %}">
<meta name="theme-color" content="#3a9fff"><link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css'><link rel="stylesheet" href="{%static 'css/stylez.css'%}">


<body>
<!-- partial:index.partial.html -->

  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" type="image/x-icon" href="{%static 'images/logo.jpg'%}"/>
<meta name="theme-color" content="#1885ed">
  <title>Tugule- Homepage</title>
</head>

<body>

  
<header class="header">
  <div class="container header__container">
<div class="header__logo"><img class="header__img" src="{%static 'images/logo.png'%}"height=70px style="border-radius: 100%;"> <h1 class="header__title">Tugule<span class="header__light"></span></h1></div> 
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
  
  <div class="header__menu">
    <nav id="navbar" class="header__nav collapse">
      <ul class="header__elenco">
        <li class="header__el"><a href="{%url 'tugule:home'%}" class="header__link">Dashboard</a></li>
        <li class="header__el"><a href="{%url 'tugule:signup'%}" class="header__link">Register now!</a></li>
        <li class="header__el"><a href="{%url 'products:home'%}" class="header__link">Products</a></li>
        
       
       
        
        <li class="header__el header__el--blue"><a href="{%url 'tugule:login'%}" class="btn btn--white">Log In →</a></li>
        <li class="header__el"><a href="{%url 'products:cart'%}"><svg xmlns="http://www.w3.org/2000/svg" width="36" height="26" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
          <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l.5 2H5V5zM6 5v2h2V5zm3 0v2h2V5zm3 0v2h1.36l.5-2zm1.11 3H12v2h.61zM11 8H9v2h2zM8 8H6v2h2zM5 8H3.89l.5 2H5zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0"/>
        </svg></a></li>
      </ul>
    </nav>
  </div>
    </div>
</header>

<div class="sect sect--padding-top">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
    <div class="site">
      <h1 class="site__title"></h1>
      <h2 class="site__title">Where Users Meet Businesses in a Click!</h2>
      
      
      
     {% include 'tugulenga/slide.html' %}
    </div>
    </div>
    </div>
  </div>
</div>




<div class="sect sect--violet ">
  <img src="https://image.ibb.co/fWyVtb/path3762.png" class="career-img">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <p class="career_title">Tugule is a commercial online webplatform designed to provide users with a seamless shopping experience. Whether your'e a customer looking for quality products or a seller aiming to showcase your merchandise. Tugule offers a platform that meets your needs.</p>
        
        
      </div>
    </div>
  </div>
  
</div>




<!-- partial -->
 
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/js/swiper.jquery.min.js'></script>
<script  src="{%static 'js/script.js'%}"></script>
<script src="{% static 'js/slides.js' %}"></script>
</body>
</html>

tugulenga/templates/tugulenga/login.html
<!DOCTYPE html>
<html>
    
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Tugule</title>
	<link rel="shortcut icon" type="image/png" href="https://image.ibb.co/fOur3b/favicon.png"/>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #2c2f2f  !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #aaadac;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #05026b !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #080500 !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{%csrf_token%}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
				{%for message in messages%}
				<p id="messages">{{message}}</p>
				{%endfor%}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'tugule:signup' %}" class="ml-2" style="color: darkblue;">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

tugulenga/templates/tugulenga/profile.html
{% extends 'tugulenga/base.html' %} {% load bootstrap5 %} {% block content %}

<form style="height: 400px;">
    <h3>Profile</h3>
    {{form}}  {% csrf_token %}

    <button class="auth" type="submit">Submit</button>
</form>
{% endblock %}

tugulenga/templates/tugulenga/signup.html
<!DOCTYPE html>
<html>
    
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Tugule</title>
	<link rel="shortcut icon" type="image/png" href="https://image.ibb.co/fOur3b/favicon.png"/>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #2c2f2f !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #77817f;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #050268 !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #080500 !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {%csrf_token%}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>

                {{form.errors}}
                
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{%url 'tugule:login'%}" class="ml-2"style="color: darkblue;">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

tugulenga/templates/tugulenga/slide.html
{%load static%}
<!-- Page Wrap -->
<div class="page-wrap">

    <div id="home-slider">
      <div class="swiper-container">
        <div class="swiper-wrapper">
          <div class="row swiper-slide swiper-slide-one">
            <div class="swiper-image" data-swiper-parallax-y="-20%">
              <div class="swiper-image-inner swiper-image-left swiper-image-one">
               <img src="{%static 'images/super.jpg'%}" height="100%">
               
              </div>
            </div>
            <div class="swiper-image" data-swiper-parallax-y="35%">
              <div class="swiper-image-inner swiper-image-right swiper-image-two">
                <img src="{%static 'images/new.webp'%}" height="100%">
              </div>
            </div>
          </div>
          <div class="swiper-slide swiper-slide-two">
            <div class="swiper-image" data-swiper-parallax-y="-20%">
              <div class="swiper-image-inner swiper-image-left swiper-image-three">
                <img src="{%static 'images/slide5.jpg'%}" height="100%">
               
              </div>
            </div>
            <div class="swiper-image" data-swiper-parallax-y="35%">
              <div class="swiper-image-inner swiper-image-right swiper-image-four" width="40%">
                <img src="{%static 'images/slide2.jpg'%}" height="100%">
              </div>
            </div>
          </div>
          <div class="swiper-slide swiper-slide-three">
            <div class="swiper-image" data-swiper-parallax-y="-20%">
              <div class="swiper-image-inner swiper-image-left swiper-image-five">
                <img src="{%static 'images/snk.jpg'%}" height="100%">
              </div>
            </div>
            <div class="swiper-image" data-swiper-parallax-y="35%">
              <div class="swiper-image-inner swiper-image-right swiper-image-six">
                <img src="{%static 'images/cloth.jpg'%}" height="100%">
              </div>
            </div>
          </div>
  
        </div>
        <div class="swiper-pagination"></div>
      </div>
    </div>
  
  </div>